In [4]:
import numpy as np

In [91]:
# 1.Create a 1D array of numbers from 0 to 9
array_new = np.arange(10)
print(array_new)

[0 1 2 3 4 5 6 7 8 9]


In [85]:
# 2.Create a 3×3 NumPy array of all Boolean value Trues
BooleanTrues = np.ones((3, 3), dtype=bool)
print(BooleanTrues)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [10]:
# 3.Extract all odd numbers from array of 1 10

odd_number = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(odd_number[odd_number % 2 == 1])


[1 3 5 7 9]


In [11]:
# 4.Replace all odd numbers in an array of 1 10 with the value 1

Number_replace = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
Number_replace[Number_replace % 2 == 1] = 1
print(Number_replace)

[ 1  2  1  4  1  6  1  8  1 10]


In [12]:
# 5.Convert a 1D array to a 2D array with 2 rows

array_1D = np.arange(14)
array_2D = array_1D.reshape(2, 7) 
print(array_2D)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]]


In [13]:
# 6.Create two arrays a and b, stack these two arrays vertically use the np.dot and np.sum to calculate totals

a = np.arange(1,10).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
print (np.vstack([a, b]))
c = np.dot(a, b)
print(c)
total_sum = np.sum(c)
print(total_sum)



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
1944


In [14]:
# Extension
# 1. Create the following pattern without hardcoding. Use only NumPy functions 

new_pattern = np.array([1,2,3])

np.r_[np.repeat(new_pattern, 3), np.tile(new_pattern, 3)]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [15]:
# 2. In two arrays a ( 1,2,3,4,5) and b ( 4,5,6,7,8,9) remove all repeating items present in array b

a = np.array([ 1, 2, 3, 4, 5])
b = np.array([ 4, 5, 6, 7, 8, 9])

print(np.setdiff1d(a,b))


[1 2 3]


In [20]:
# 3. Get all items between 3 and 7 from a and b and sum them together
import numpy as np
a = np.array([ 1, 2, 3, 4, 5])
b = np.array([ 4, 5, 6, 7, 8, 9])
join_ab = np.concatenate((a, b))

# Extract all items between 3 and 7 ==> Note: Thus, the range to extract will include (3, 4, 5, 6, 7)]
extract = join_ab [(3 <= join_ab) & (join_ab <= 7)]
print(extract)
print(sum(extract))


[3 4 5 4 5 6 7]
34
